Update abiencoder.go for compatible with double quoted string to number.
eoscanada/eos-go pull request #208
Opened 2023-05-31 08:03 UTC by yjwxfq

Because the params of number with quotation marks are supported on the command of cleos push action.

2023-05-31 13:55 UTC, maoueh requested changes
Please adjust the code to use:

```
strings.Trim(..., `"`)
```

Everywhere and please add a CHANGELOG.md entry.

2023-05-31 13:55 UTC, maoueh commented on abiencoder.go
> +	i, err := strconv.ParseInt(s, 10, bitSize)
```suggestion
    // Explain here why we do this please
	i, err := strconv.ParseInt(strings.Trim(value.Raw, `"`), 10, bitSize)
```

This is exactly equivalent as the code you did with the same performance profile, trimming is a no-op in Go is the prefix/suffix is not present.

2023-05-31 13:55 UTC, maoueh commented
A unit test also would be welcomed

2023-06-07 06:27 UTC, yjwxfq commented
strings.Trim will modify the original string. Besides, I just want to be compatible such as "12345" string sumber, not all " are compatible such as "12"345"

2023-06-07 13:55 UTC, maoueh commented
> strings.Trim will modify the original string. Besides, I just want to be compatible such as "12345" string sumber, not all " are compatible such as "12"345"

`Trim` gives you a slice of the original string, the original is still untouched. Also, `Trim` is for leading/trailing characters only, it don't remove double quotes in the middle of a string.

See https://go.dev/play/p/LHuEjbDKB6v

2023-06-08 03:07 UTC, yjwxfq commented
You are right. Thank you very much for letting me learn this new knowledge.
I have modified the code as you suggested.

2023-06-08 16:09 UTC, maoueh commented
@yjwxfq All is good, can you add an entry in [CHANGELOG.md](./CHANGELOG.md), I'll merge afterward.

2023-06-09 05:06 UTC, yjwxfq commented
@maoueh OK, CHANGELOG.md is done.

2023-06-09 18:00 UTC, maoueh approved these changes

2023-06-09 18:00 UTC, merged